version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=devpassword
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - ./data/mongo:/data/db
